version: '3'

networks:
  app_network:
    external: true

services:
  # mysql:
  #   image: mysql
  #   environment:
  #     MYSQL_DATABASE: 'student_records'
  #     MYSQL_ROOT_PASSWORD: 'root'

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "5000:5000"

  consumer1:
    build:
      context: ./consumer1
      dockerfile: Dockerfile
    container_name: consumer1
    depends_on:
      - producer
    
    
  consumer2:
    build:
      context: ./consumer2
      dockerfile: Dockerfile
    container_name: consumer2
    depends_on:
      - producer
    
  consumer3:
    build:
      context: ./consumer3
      dockerfile: Dockerfile
    container_name: consumer3
    depends_on:
      - producer
    

  consumer4:
    build:
      context: ./consumer4
      dockerfile: Dockerfile
    container_name: consumer4
    depends_on:
      - producer
    
    