version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/"
    networks:
      - rabbitmq
    # volumes:
    #   - rabbitmq-data:/var/lib/rabbitmq

  http-server:
    build: ./producer
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
    networks:
      - default

  health-check:
    build: ./consumer_one
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
    networks:
      - default

  insertion:
    build: ./consumer_two
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
    networks:
      - default

  retrieval:
    build: ./consumer_four
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
    networks:
      - default

  deletion:
    build: ./consumer_three
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: "guest"
      RABBITMQ_PASSWORD: "guest"
    networks:
      - default

networks:
  rabbitmq:
    driver: bridge
  default:
    driver: bridge

volumes:
  rabbitmq-data:
